### ISSUE TITLE
Game crashing when trying to remove exotic

### ISSUE THREAD

**Issue by Darudado** [scardwell15/ExoticaTechnologies#8]
![immagine](https://github.com/scardwell15/ExoticaTechnologies/assets/22028695/9b821ed4-0e44-4754-ba65-ce211a463d35)
The game crashes when clicking that.
LOGS:
251338 [Thread-3] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.NullPointerException
java.lang.NullPointerException
	at exoticatechnologies.ui.impl.shop.overview.OverviewPanelUIPlugin$ClearExoticsButtonHandler.checked(OverviewPanelUIPlugin.kt:155)
	at exoticatechnologies.ui.InteractiveUIPanelPlugin.advance(InteractiveUIPanelPlugin.kt:27)
	at com.fs.starfarer.ui.newui.int.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.advance(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.advance(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.impl.StandardTooltipV2.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.impl.StandardTooltipV2Expandable.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.advance(Unknown Source)
	at com.fs.starfarer.ui.impl.StandardTooltipV2.advance(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.newui.int.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.advance(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.advance(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.impl.StandardTooltipV2.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.impl.StandardTooltipV2Expandable.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.advance(Unknown Source)
	at com.fs.starfarer.ui.impl.StandardTooltipV2.advance(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.newui.int.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.advance(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.advance(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.impl.StandardTooltipV2.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.impl.StandardTooltipV2Expandable.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.advance(Unknown Source)
	at com.fs.starfarer.ui.impl.StandardTooltipV2.advance(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.newui.int.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.advance(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.advance(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.impl.StandardTooltipV2.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.impl.StandardTooltipV2Expandable.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.advance(Unknown Source)
	at com.fs.starfarer.ui.impl.StandardTooltipV2.advance(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.newui.int.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.advance(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.newui.int.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.advance(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.public.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.newui.L.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.advance(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.advance(Unknown Source)
	at com.fs.starfarer.campaign.CampaignState.advance(Unknown Source)
	at com.fs.starfarer.BaseGameState.traverse(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:750)

**Comment by OfficialZygorg** [comment]
Getting the same error here with 1.7.1
